language: java

addons:
  sonarcloud:
    organization: "julg"
    token:
       secure: "kKGKzMEK/KyMGHWhVnQHQNxs3M15B4kGFwBWvzVSwY9eZCP0F9KGyJRC6Qeul0cwfJTGXqj7yhKkWbTk684Y3qsSrRrBpKmhttGRrzTj/Tn4PFMoQhncjYfg8dUdA7+Bhet/3Ouko6+JYMEnaKLTZ84dUWhj3wX+TP8FledqgqZ7716k0En9J/hP89AEKbOoNHqvNg7KRQeRdoyj4yA+3huS2jms0NgW9TXCcU5ePtlJd4wu/0o1RHIkCL33CnEg4PhROmlGHkJOBlhrlHD/8L22zP+WDavJMY661pjQ2WyVq4xcdG29KsvFFclu3HR4TNcY+aHZiVhqfvX7aZ4pF3JXrnNlGI1ZEXAP2FfCD81cD+ze7fTttAsjgdFQX6U7L69bAjxASP3TClPYBo2aec9XfuHUYinstd99eo92aHsYDk2LkTUU3om3yzp+wKT1jA1q3K6QNTDY4CQeeaP55clrssBxyiVldvn/o0q2wM1UgNe4i6dzJokK387KQH1LzjWRC3lZPJoRd0pMU60a2udHpX4ShoHrIVhYUcYSjGmlkesd/yr4hIVu5VwLxS79pR2aZPpMNo6OSz9KEucuN3zDkS0r8iySIZF3sTy+VcB64BVXu8Yy+Es/zOdoq9Uc3pQAoYL9T/w5owx9vzHQ0pzIZ5q+6y867qM+G5c/o9U="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=julg_apitheses

notifications:
  slack:
    rooms:
      - secure: "FNNBqRvl4BGxgcEWETD/gYCUzqVSVaPEUUdzfV4bC/Id7WXLrcgn/BW+NBt63ndAftwrjGIgQCbLXSIrlUqxV1cje9yAaBjOzW+ceoesEIzY4iFMQv7WQu2UqRUUai/5/QNvowJ8mO188wzXmlmAi01ZyS5+/oHOM+XoA0uEEz1TLVCVTj3hie4Cg+QNj5DOl3rLnDZ9ThP1iCDMOoOuSemG4bMG748QkqWNAvFJcAKLYgQBAN3Uf+ejZQxVWPm1CzJJ2dmHcZIM/K7SzBIuEU8Yb69MW/o/dSxg15AdOSyWHD/AobqIQWEWsFahFOHDEG+GTH5oiiOuzoUo7c1a6c8rKzESZTLG6LfuVuyvMtK07DzPqkSfIkHJvP/E1Hv6WDrDZ8iyqfxcsUn1lqRMHCNrPT3C85gf04ZIX3LwdZx7oCPZzdFPdwQJEyw9LaDI5IuhLHXckg3nB0qodgIH3+YxiXe6q9xoEf5/RlwbPHq93a6jkYJq5BtnYAw+gDzqPB1S3x5Krh46dDirLHqvIZUuu/tJ7zlOwR2uND/3zo5otQ9C6f5F6BJ0tCqB5+jau78oFAFX9GfjTBjXY1WG6D9pKibkGh7e+Enh77Dxr454eKcBV0UtUnI+q5xjy8U8/GSLj1Teu6VJKQcjiEt0SzEzrQk879cpA6bM0pHMYJs="

